services:
  app:
    image: blogilista-front
    build:
      context: ../osa5/blogilista-frontend
      dockerfile: Dockerfile

  server:
    image: blogilista-back
    build:
      context: ../osa4/blogilista
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/bloglist
      - SECRET=${SECRET:-productionsecret}
      - PORT=3003
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: bloglist
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  nginx:
    image: nginx:1.29-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app
      - server

volumes:
  mongo_data:
